//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_ERP1.Db_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailConfig
    {
        public int Config_id { get; set; }
        public Nullable<int> Config_port { get; set; }
        public string Config_host { get; set; }
        public string from_mail_id { get; set; }
        public string from_password { get; set; }
    }
}
