//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_ERP1.Db_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTemplate
    {
        public int template_id { get; set; }
        public string template_subject { get; set; }
        public string template_body { get; set; }
        public string flag { get; set; }
    }
}
