//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_ERP1.Db_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_Request_Line
    {
        public int Request_Line_Id { get; set; }
        public Nullable<int> Request_Header_Id { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public Nullable<int> Item_Id { get; set; }
        public Nullable<decimal> Qty { get; set; }
    }
}
