//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_ERP1.Db_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Line_Table
    {
        public int Purchase_Line_Id { get; set; }
        public Nullable<int> Purchase_Header_Id { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public Nullable<int> Item_Id { get; set; }
        public Nullable<int> Tax_Id { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Tax_Amount { get; set; }
        public Nullable<decimal> Discount_Percentage { get; set; }
        public Nullable<decimal> Basic_Amount { get; set; }
        public Nullable<decimal> Tax_Total_Amount { get; set; }
        public Nullable<decimal> Discount_Amount { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
    }
}
