//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_ERP1.Db_Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Db_Production_Entities : DbContext
    {
        public Db_Production_Entities()
            : base("name=Db_Production_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User_Registration> User_Registration { get; set; }
        public virtual DbSet<EmailConfig> EmailConfigs { get; set; }
        public virtual DbSet<EmailTemplate> EmailTemplates { get; set; }
        public virtual DbSet<Client_Registration> Client_Registration { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Person_Type> Person_Type { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Tax> Taxes { get; set; }
        public virtual DbSet<PO_Request_Header> PO_Request_Header { get; set; }
        public virtual DbSet<PO_Request_Line> PO_Request_Line { get; set; }
        public virtual DbSet<Purchase_Header> Purchase_Header { get; set; }
        public virtual DbSet<Purchase_Line_Table> Purchase_Line_Table { get; set; }
    
        public virtual int UpdateOtp(string email_Id, string otp)
        {
            var email_IdParameter = email_Id != null ?
                new ObjectParameter("Email_Id", email_Id) :
                new ObjectParameter("Email_Id", typeof(string));
    
            var otpParameter = otp != null ?
                new ObjectParameter("Otp", otp) :
                new ObjectParameter("Otp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateOtp", email_IdParameter, otpParameter);
        }
    
        public virtual ObjectResult<GetAllReport_Result> GetAllReport(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllReport_Result>("GetAllReport", userIdParameter);
        }
    
        public virtual int spGetClientReport(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGetClientReport", userIdParameter);
        }
    
        public virtual ObjectResult<spGetItemReport_Result> spGetItemReport(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetItemReport_Result>("spGetItemReport", userIdParameter);
        }
    
        public virtual ObjectResult<spGetPerson_TypeReport_Result> spGetPerson_TypeReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetPerson_TypeReport_Result>("spGetPerson_TypeReport");
        }
    
        public virtual ObjectResult<spGetPersonReport_Result> spGetPersonReport(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetPersonReport_Result>("spGetPersonReport", userIdParameter);
        }
    
        public virtual ObjectResult<spGetProductReport_Result> spGetProductReport(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetProductReport_Result>("spGetProductReport", userIdParameter);
        }
    
        public virtual ObjectResult<spGetTaxReport_Result> spGetTaxReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetTaxReport_Result>("spGetTaxReport");
        }
    
        public virtual ObjectResult<string> SpLineHedar(Nullable<int> request_Header_Id)
        {
            var request_Header_IdParameter = request_Header_Id.HasValue ?
                new ObjectParameter("Request_Header_Id", request_Header_Id) :
                new ObjectParameter("Request_Header_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SpLineHedar", request_Header_IdParameter);
        }
    
        public virtual ObjectResult<string> TestSp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("TestSp");
        }
    
        public virtual ObjectResult<string> Sp_JoinLine()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Sp_JoinLine");
        }
    
        public virtual ObjectResult<sp_joinHeader_Result> sp_joinHeader(Nullable<int> request_Header_Id)
        {
            var request_Header_IdParameter = request_Header_Id.HasValue ?
                new ObjectParameter("Request_Header_Id", request_Header_Id) :
                new ObjectParameter("Request_Header_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_joinHeader_Result>("sp_joinHeader", request_Header_IdParameter);
        }
    
        public virtual ObjectResult<spGetClientReports_Result> spGetClientReports(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetClientReports_Result>("spGetClientReports", userIdParameter);
        }
    }
}
