//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_ERP1.Db_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Registration
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email_Id { get; set; }
        public string User_Password { get; set; }
        public string Verify { get; set; }
        public string Profile_Image { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    }
}
